import { signIn } from 'next-auth/react';
import Head from 'next/head';
import bg from 'public/pexels-victor-freitas-791763.jpg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bel Effort App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero min-h-full" style={{ backgroundImage: `url(${bg.src})` }}>
        <div className="hero-overlay bg-opacity-60"></div>
        <div className="hero-content text-center text-neutral-content">
          <div className="max-w-md">
            <h1 className="mb-5 text-5xl font-bold">BelEffort</h1>
            <p className="mb-5">
              Track Your Gains, Set New PRs! Record and Save Your Best Performances for Multiple Weightlifting Movements
              with Ease.
            </p>
            <p className="mb-5">
              Beleffort allows you to effortlessly track your PRs for various sets and repetitions. Plus, our app
              includes a handy calculator that estimates your theoretical 1RM based on your recorded PRs, helping you
              set achievable goals and push your limits. Join Beleffort now and elevate your weightlifting game to new
              heights!
            </p>
            <button className="btn-primary btn" onClick={() => signIn(undefined, { callbackUrl: '/' })}>
              Get Started
            </button>
          </div>
        </div>
      </div>
    </>
  );
}
